version: '3.4'

services:
  users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "6001:80"
    networks:
      - my-network

  webappsite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5001:80"
    networks:
      - my-network

  seq:
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./seq-data:/data
    networks:
      - my-network

networks:
  my-network:
    external: true