version: '3.8'

services:
  users.api:
    container_name: vos-usersapi
    image: ${DOCKER_REGISTRY}/usersapi:${TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_SERVER_NAME=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_USER_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - backend

  webappsite:
    container_name: vos-webapp
    image: ${DOCKER_REGISTRY}/webappsite:${TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HOST_USERS_API=vos-usersapi
    ports:
      - "5001:80"
    networks:
      - backend

  mysql:
    container_name: mysql
    image: ${DOCKER_REGISTRY}/mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
