version: '3.4'

services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Users/Dockerfile

  webappsite:
    image: ${DOCKER_REGISTRY-}webappsite
    build:
      context: .
      dockerfile: src/WebAppSite/Dockerfile
    environment:
        - API_URL=users.api:80

  seq:
    image: datalust/seq:2020.1.4164-pre
    container_name: seq